

******** Functional Trace ********

Problem:	A dependency issued 1 warning(s)

            Warning 0           : Test warning for Warning Utils
            ... from            : <APODEIXI INSTALLATION>/apodeixi/util/tests_unit/test_warning_utils.py
            ... at line         : 24
            Stack Trace         : 
------------------------------------------------------------	Warnings Stack Trace

  File "<PYTHON MODULE>/runpy.py", line <HIDDEN>, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<PYTHON MODULE>/runpy.py", line <HIDDEN>, in _run_code
    exec(code, run_globals)
  File "<PYTHON MODULE>/unittest/__main__.py", line <HIDDEN>, in <module>
    main(module=None)
  File "<PYTHON MODULE>/unittest/main.py", line <HIDDEN>, in __init__
    self.runTests()
  File "<PYTHON MODULE>/unittest/main.py", line <HIDDEN>, in runTests
    self.result = testRunner.run(self.test)
  File "<PYTHON MODULE>/unittest/runner.py", line <HIDDEN>, in run
    test(result)
  File "<PYTHON MODULE>/unittest/suite.py", line <HIDDEN>, in __call__
    return self.run(*args, **kwds)
  File "<PYTHON MODULE>/unittest/suite.py", line <HIDDEN>, in run
    test(result)
  File "<PYTHON MODULE>/unittest/suite.py", line <HIDDEN>, in __call__
    return self.run(*args, **kwds)
  File "<PYTHON MODULE>/unittest/suite.py", line <HIDDEN>, in run
    test(result)
  File "<PYTHON MODULE>/unittest/suite.py", line <HIDDEN>, in __call__
    return self.run(*args, **kwds)
  File "<PYTHON MODULE>/unittest/suite.py", line <HIDDEN>, in run
    test(result)
  File "<PYTHON MODULE>/unittest/case.py", line <HIDDEN>, in __call__
    return self.run(*args, **kwds)
  File "<PYTHON MODULE>/unittest/case.py", line <HIDDEN>, in run
    self._callTestMethod(testMethod)
  File "<PYTHON MODULE>/unittest/case.py", line <HIDDEN>, in _callTestMethod
    method()
<APODEIXI INSTALLATION>/apodeixi/util/tests_unit/test_warning_utils.py", line 24, in test_warning_utils
    warnings.warn("Test warning for Warning Utils", DeprecationWarning)
  File "<PYTHON MODULE>/warnings.py", line <HIDDEN>, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
<APODEIXI INSTALLATION>/apodeixi/util/warning_utils.py", line 49, in _warn_with_traceback
    traceback.print_stack(file=log)
<APODEIXI INSTALLATION>/apodeixi/util/tests_unit/test_warning_utils.py:24: DeprecationWarning: Test warning for Warning Utils
  warnings.warn("Test warning for Warning Utils", DeprecationWarning)

------------------------------------------------------------

Here are the functional activities that led to the problem (stack trace at the bottom):

---->	activity	Testing Warning Utils


---->	activity	Testing a fake warning


------------------------------------------------------------	Technical Stack Trace

Traceback (most recent call last):
<APODEIXI INSTALLATION>/apodeixi/util/tests_unit/test_warning_utils.py", line 26, in test_warning_utils
    WarningUtils().handle_warnings(my_trace, warning_list=w)
<APODEIXI INSTALLATION>/apodeixi/util/warning_utils.py", line 183, in handle_warnings
    raise ApodeixiError(parent_trace, "A dependency issued " + str(len(warning_list)) + " warning(s)",
<APODEIXI INSTALLATION>/apodeixi.util.a6i_error.ApodeixiError: (ApodeixiError(...), 'A dependency issued 1 warning(s)')

------------------------------------------------------------